apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "fastapi.fullname" . }}
    labels:
        {{ include "fastapi.labels" . | indent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      role: fastapi
  template:
    metadata:
      labels:
        role: fastapi
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"